### ISSUE TITLE
Delay to response request

### ISSUE THREAD

**Issue by fontolangustavo** [adonisjs/core#1217]
Hi everyone,
i have a problem in delay my request, in local request 7~9 ms and serve request 1.2s, i don't know why this giant delay, can anybody help me?
## Request
![WhatsApp Image 2020-03-10 at 14 41 47](https://user-images.githubusercontent.com/3093772/76344834-fcb2e400-62e0-11ea-9c68-d5882e319fdd.jpeg)

## Delay response
![WhatsApp Image 2020-03-10 at 14 41 27](https://user-images.githubusercontent.com/3093772/76344851-02a8c500-62e1-11ea-8142-d1644ea3af47.jpeg)

## Package version
![WhatsApp Image 2020-03-10 at 14 48 45](https://user-images.githubusercontent.com/3093772/76344791-eefd5e80-62e0-11ea-9b6e-4640cb96feb7.jpeg)

**Comment by McSneaky** [comment]
It's most likely due to ping to server + host server load.
It may take quite a lot to send request packages over to the other side of world and get response back and when host server is under heavy load it might queue up request and start processing it when it gets free resources

If that happens check server load. But there are more a lot of things, that can increase the response time

**Comment by thetutlage** [comment]
I believe, we should move discussions like this to the discord and keep the issues board clean.

Going to close it
