### ISSUE TITLE
Schema array validator not converting HTTP request data from string to array

### ISSUE THREAD

**Issue by D-Marc1** [adonisjs/core#1836]
The documentation for Adonis 5 states that using schema validations will convert it from a string to the correct type, but this doesn't work for me. I've attempted to pass the data into both the `body` and `URL params`, but both are simply not converting the string to an array. Oddly enough, I see it returned correctly as a an array if I return it in the controller as the response.

## Package version
5.0.4-preview-rc-2

## Node.js and npm version

node -v: 12.18.3

npm -v: 6.14.8

## Sample Code (to reproduce the issue)

```js
const userSchema = schema.create({
  categories: schema.array([rules.minLength(1)]).members(schema.number()),
});

const { categories } = await request.validate({
  schema: userSchema,
});
```

I get the following response:

```json
{
  "errors": [
    {
      "rule": "array",
      "field": "categories",
      "message": "array validation failed"
    }
  ]
}
```

**Comment by thetutlage** [comment]
> The documentation for Adonis 5 states that using schema validations will convert it from a string to the correct type, but this doesn't work for me

Since everything over HTTP is represented as a string. AdonisJS attempts to cast values to their original data types. But that is limited to data types that can be casted. For example:

- Converting `'22'` to `22`
- Converting `'false'` to false

There is no way to convert a string to array. Do you expect the value to split using a `comma` or `pipe` or a `space`. There are simply to many combinations.

HTML natively allows submitting arrays via forms and hence this transformation is not even required.

Also I recommend using Github discussions and do not create issues until it has been confirmed as an issue

**Comment by D-Marc1** [comment]
I asked this as an issue, because I actually thought it was one, due to how the documentation is worded. I'd be happy to send a pull request if you'd like to clarify. I'm sure other people would be confused by it too.

Using `FormData` doesn't even work for me in Adonis 5 though.

**Comment by darkegn** [comment]
I was having the same problem, classic solution

  ```JS

const selectedCategoryIds = ["6519a9837374b492c3430d28","651a01d7528eb0e67da26b1b"]

let formData = new FormData(); 

selectedCategoryIds.forEach((value, index) => {
               formData.append(`categories[${index}]`, value);
               });

```
> I asked this as an issue, because I actually thought it was one, due to how the documentation is worded. I'd be happy to send a pull request, if you'd like, to clarify. I'm sure other people would be confused by it too.
> 
> Using `FormData` (multipart/form-data) doesn't even work for me in Adonis 5 though.
