### ISSUE TITLE
VSCODE auto import of some '@ioc:Adonis/Core/*' modules not working

### ISSUE THREAD

**Issue by ad-on-is** [adonisjs/core#2223]
I just realized when working in VSCODE, the auto import functionality of '@ioc:Adonis/Core/*' does not work.

## Expected behavior
Type `Log...` => suggest `Logger` in dropdown list and import `@ioc:Adonis/Core/Logger`
Type `Http...` => suggest `HttpContextContract` in dropdown list and import `@ioc:Adonis/Core/HttpContext`

## Actual behavior
Type `Log...` => nothing suggested
Type `Http` => suggests `HttpContext`, `HttpExceptionHandler`, but **NOT** `HttpContextContract`

Do I have to configure something separately to make this work?

**Comment by thetutlage** [comment]
I am not sure how come this is an issue with the framework. If you need general help, then simply use discussions. Issues are for reporting bugs with the framework

**Comment by ad-on-is** [comment]
@grantholle You're having a bad day, aren't you? 
First, you lesson someone to use the search (https://github.com/adonisjs/core/issues/2219) and now you're being rude telling me that I don't know the difference between an issue and a discussion.

Dude, you know, you can point people to a solution without being hoity-toity. 👍

**Comment by thetutlage** [comment]
You can also be respectful to others time by choosing the correct medium of communication. This is not something we follow, every community on Github asks you to choose the right medium.

When you open a new issue, you are presented with two templates. This issue is not a bug and neither a feature request. The link in the bottom left is when you are 100% sure that this needs to be reported as issue and discussing in the forum is not an option

<img width="1279" alt="Screenshot 2021-02-07 at 8 29 39 PM" src="https://user-images.githubusercontent.com/1706381/107150345-5b665f00-6983-11eb-938c-d6c8b7f2620f.png">

By knowing that this is not a direct issue in the code. You can start by discussing this inside the discussion forum.

Regarding, asking someone to search. I am not sure how that is rude. I did the same thing. I searched in the discussion forum and pasted the link. Just imagine, everyone opening new threads without searching old one, is like asking me to search for them. I am happy to search, if you can pay for it 🙂

**Comment by ad-on-is** [comment]
>You can also be respectful to others time by choosing the correct medium of communication.
Firstly, respect is a bi-directional thing. Absolutely no one here, is forcing anybody to spend their time in answering questions. And if someone feels the urge to post any kind of answer, this should be done in a respectful manner.

> every community on Github asks you to choose the right medium.
Sure, and still they do it respectfully

Secondly, what is and what is not an issue, is sometimes a blurred line. Like in this case, where I encountered, that it works with some modules, while it doesn't work with others. So my assumption was, that it must have to do with the framework. Therefore, I did exactly as you said: 

> The link in the bottom left is when you are 100% sure that this needs to be reported as issue and discussing in the forum is not an option

And now we ended up being here! 😁

**Comment by thetutlage** [comment]
> Absolutely no one here, is forcing anybody to spend their time in answering questions

For this you should use the discussion forum. The issues are exclusively for reporting bugs and I look at them on priority. As the creator of the framework, I do have the right to decide what will/should end up in the issues.
