### ISSUE TITLE
Form Request Validation

### ISSUE THREAD

**Issue by Babunashvili** [adonisjs/core#2350]
Please consider answering the following questions before opening the issue:

- [x] Do you have the complete context of the feature and how it should be implemented?
- [x] Do you have a clear understanding of the final outcome?
- [ ] Will you be available to work on the feature?
- [ ] Can you write the necessary documentation for the feature?

## Why this feature is required (specific use-cases will be appreciated)?
Like Laravel, for more complex validation scenarios, you may wish to create a "form request". Form requests are custom request classes that contain validation logic.

The form request class also contains an authorize method. Within this method, you may check if the authenticated user actually has the authority to update a given resource

## Have you tried any other workarounds?
```
const validated = await request.validate({
    schema: schema.create({
      marks: schema.number() // 👈 convert to number and validate
    })
 })
```

This example is mentioned in the Adonis guide but I need to have the validation and authorize methods in a separate class.

```
class CreateUserRequest{

     public authorize(){
        return true
     }
     
     public rules(){
        return schema: schema.create({
            marks: schema.number() // 👈 convert to number and validate
        })
     }
     
}
```

**Comment by RomainLanz** [comment]
Hey @Babunashvili! 👋 

There is no `authorize` method in V5 validation.

➡️ https://preview.adonisjs.com/guides/validator/introduction
➡️ https://preview.adonisjs.com/guides/http/form-submissions#using-validator-classes

Also, this is more a question than an issue with the framework.
Please, if you have any questions, [create a discussion thread](https://github.com/adonisjs/core/discussions) instead of an issue.
