### ISSUE TITLE
Querying month(date) not giving result after upgrading to stable release

### ISSUE THREAD

**Issue by hunkaf** [adonisjs/core#2605]
After upgrading to stable release from preview, date functions (eg. MONTH, YEAR, QUARTER...) stopped giving result:

## Sample Code (to reproduce the issue)
```
const result = await MyModel.query().select(Database.raw('month(date)')).debug(true)
```

Debug shows the SQL as below:
```
SELECT MONTH(DATE) FROM `my_table`
```

## Actual outcome
```
{
    "result": [
        {},
        {},
        {},
        {}
    ]
}
```

In preview release, this was working and grouping also like this:
```
const result = await MyModel.query()
      .select(Database.raw('month(date)'))
      .sum('some_field')
      .groupBy(Database.raw('month(date)').sql)
      .debug(true)
```

Debug shows the SQL as below:
```
SELECT MONTH(`DATE`) FROM `res_cube` GROUP BY MONTH(`DATE`)
```

SQL looks good in both cases. 
Thanks in advance!

**Comment by thetutlage** [comment]
The issue is in the wrong repo and also the query you have shared working in the preview release is different from the query you claim is not working.

Also, the output of model queries is never plain objects, so the actual outcome you have shared is wrong or over simplified.

Please, open a discussion thread instead and share the exact output of the `console.log(result)`
