### ISSUE TITLE
Server Api Timeout issue

### ISSUE THREAD

**Issue by satheesr** [adonisjs/core#2913]
Hi team,

I have connected postgres with adonis server. There are couple of endpoints that has huge data and load time is more. But after a minute, I am getting timeout error. Below is the sample code that I tried in vowfile.js 

## Package version

 "@adonisjs/vow": "^1.0.17",
## Node.js and npm version

"adonis-version": "4.1.0",

## Sample Code (to reproduce the issue)
module.exports = (cli, runner) => {
  runner.before(async () => {
    // Check database
    const DBname = Env.get('DB_DATABASE');
    if (!(DBname.includes('test') || DBname.includes('postgres'))) {
      throw new Error(`Use test DB instead of ${DBname}`);
    }

    // Start the server
    const Server = use('Adonis/Src/Server').listen(process.env.HOST, process.env.PORT);
    **Server.getInstance().timeout = 0;**

    // Refresh database
    await ace.call('migration:refresh', {}, { silent: true });
    await ace.call('seed', {}, { silent: true });
  });

  runner.after(async () => {
    // Shutdown server
    use('Adonis/Src/Server').getInstance().close();
  });
};

## Other methods
I also tried solution to issue #877 and #434 and no luck.

This is what I tried in server.js

```
const { Ignitor } = require('@adonisjs/ignitor')

new Ignitor(require('@adonisjs/fold'))
    .appRoot(__dirname)
    .fireHttpServer()  
    .then(() => {
        use('Adonis/Src/Server').getInstance().timeout = 0;
        use('Logger').info(`Server timeout: ${use('Adonis/Src/Server').getInstance().timeout}`);
    })  
    .catch(console.error)
```

**Comment by thetutlage** [comment]
There can be a 1000 different reasons for a request to timeout. So you have to debug it yourself and see why. The timeout can happen by the AdonisJS server, or the client sending the request or even it can be the database server.

Also, I recommend using the [discussions forum](https://github.com/adonisjs/core/discussions) to ask your questions and please format the code properly, so that others can understand it and provide help :)
