### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource. While CORS settings are set to '*'

### ISSUE THREAD

**Issue by zarbi4734** [adonisjs/core#2915]
Hello, I have a bug when i'm trying to do a XMLHttprequest to my adonisjs api:
`Access to XMLHttpRequest at 'https://myapiip:3333/route' from origin 'https://mywebsite.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

The server is running node **v16.5.0** and the latest version of adonisJS 5

I've checked the cors settings in adonisjs, The cors is enabled (set to true) and I'm allowing all origins (origin: '*').

Here is  my XMLHttprequest:

```
const username = document.getElementById('usr152').value;
const productId = document.getElementById('usrdata5').value;
const userlicenseId = document.getElementById('usrfield17').value;
const userId = document.getElementById('usrlogininfo8').value;



function apiRequestHwidReset() {

    var url = "https://myapiip/route";

    var xhr = new XMLHttpRequest();
    xhr.open("POST", url);

    xhr.setRequestHeader("Content-Type", "application/json");

    xhr.onreadystatechange = function () {
        if (xhr.readyState === 4) {
            console.log(xhr.status);
            console.log(xhr.responseText);
        }
    };

    var data = `{
        "username": "skdf",
        "productId": "11",
        "userId":"1",
        "productkey":"5",
        "hwid":"45465"
    }`;
    xhr.send(data);
}

```
If someone have a solution it would be very helpfull thanks !

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**

**Comment by zarbi4734** [comment]
Okay my bad sorry

**Comment by undernightcore** [comment]
Well it seems like I am having the exact same problem. Cors headers are missing but my cors.ts looks like this.
`/**
 * Config source: https://git.io/JfefC
 *
 * Feel free to let us know via PR, if you find something broken in this config
 * file.
 */

import type { CorsConfig } from '@ioc:Adonis/Core/Cors'

const corsConfig: CorsConfig = {
  /*
  |--------------------------------------------------------------------------
  | Enabled
  |--------------------------------------------------------------------------
  |
  | A boolean to enable or disable CORS integration from your AdonisJs
  | application.
  |
  | Setting the value to `true` will enable the CORS for all HTTP request. However,
  | you can define a function to enable/disable it on per request basis as well.
  |
  */
  enabled: true,

  // You can also use a function that return true or false.
  // enabled: (request) => request.url().startsWith('/api')

  /*
  |--------------------------------------------------------------------------
  | Origin
  |--------------------------------------------------------------------------
  |
  | Set a list of origins to be allowed for `Access-Control-Allow-Origin`.
  | The value can be one of the following:
  |
  | https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin
  |
  | Boolean (true)    - Allow current request origin.
  | Boolean (false)   - Disallow all.
  | String            - Comma separated list of allowed origins.
  | Array             - An array of allowed origins.
  | String (*)        - A wildcard (*) to allow all request origins.
  | Function          - Receives the current origin string and should return
  |                     one of the above values.
  |
  */
  origin: '*',

  /*
  |--------------------------------------------------------------------------
  | Methods
  |--------------------------------------------------------------------------
  |
  | An array of allowed HTTP methods for CORS. The `Access-Control-Request-Method`
  | is checked against the following list.
  |
  | Following is the list of default methods. Feel free to add more.
  */
  methods: ['GET', 'HEAD', 'POST', 'PUT', 'DELETE'],

  /*
  |--------------------------------------------------------------------------
  | Headers
  |--------------------------------------------------------------------------
  |
  | List of headers to be allowed for `Access-Control-Allow-Headers` header.
  | The value can be one of the following:
  |
  | https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Request-Headers
  |
  | Boolean(true)     - Allow all headers mentioned in `Access-Control-Request-Headers`.
  | Boolean(false)    - Disallow all headers.
  | String            - Comma separated list of allowed headers.
  | Array             - An array of allowed headers.
  | Function          - Receives the current header and should return one of the above values.
  |
  */
  headers: true,

  /*
  |--------------------------------------------------------------------------
  | Expose Headers
  |--------------------------------------------------------------------------
  |
  | A list of headers to be exposed by setting `Access-Control-Expose-Headers`.
  | header. By default following 6 simple response headers are exposed.
  |
  | Cache-Control
  | Content-Language
  | Content-Type
  | Expires
  | Last-Modified
  | Pragma
  |
  | In order to add more headers, simply define them inside the following array.
  |
  | https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers
  |
  */
  exposeHeaders: [
    'cache-control',
    'content-language',
    'content-type',
    'expires',
    'last-modified',
    'pragma',
  ],

  /*
  |--------------------------------------------------------------------------
  | Credentials
  |--------------------------------------------------------------------------
  |
  | Toggle `Access-Control-Allow-Credentials` header. If value is set to `true`,
  | then header will be set, otherwise not.
  |
  | https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Credentials
  |
  */
  credentials: true,

  /*
  |--------------------------------------------------------------------------
  | MaxAge
  |--------------------------------------------------------------------------
  |
  | Define `Access-Control-Max-Age` header in seconds.
  | https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Max-Age
  |
  */
  maxAge: 90,
}

export default corsConfig
`

**Comment by CoreyVincent** [comment]
I just started having the same issue as well.
@zarbi4734 @undernightcore @thetutlage 
Anyone figure out why this is happening?

**Comment by undernightcore** [comment]
@CoreyVincent have you tried using origin='*'? I avoid using origin=true, it will try to dynamically allow origin of the request which in my case didn't work.

**Comment by CoreyVincent** [comment]
> 

@undernightcore I did, I tried `origin=true`, `origin="*"`, and `origin=["mydomain.com"]`. All of them give me the error. I looked at my server settings too on my DigitalOcean App platform where I'm hosting, and there isn't any way to change CORS there, so I can't imagine that's overriding it. It only seems to happen for one of my routes though. So I'm wondering if that has something to do with it...
Adonis Route
```ts

Route.group(() => {
  Route.post("", "DocumentsController.store")
  Route.put("/:id", "DocumentsController.update")
  Route.delete("/:id", "DocumentsController.delete")
})
  .prefix("/admin/documents")
  .middleware("auth")
```
Axios vue controller:
```ts
const formData = new FormData()
formData.append("name", data.name)
formData.append("description", data.description)
formData.append("category", data.category)
if (data.file && !_.isEmpty(data.file)) {
  formData.append("file", data.file[0].file)
}

const response: AxiosResponse = await api.put(`admin/documents/${data.id}`, formData, {
  timeout: 599000,
  headers: {
    "Content-Type": "multipart/form-data",
    Accept: "application/json",
  },
  onUploadProgress: async function ({ loaded, total }) {
    // const { loaded, total } = progressEvent
    const documentStore = useDocumentStore()
    // await Math.round((loaded * 100) / total)
    documentStore.uploadPercentage = Math.round((loaded * 100) / total!)
  },
  maxRedirects: 0,
})
```

**Comment by undernightcore** [comment]
Your cors config look OK, can I have a screenshot of the CORS error? Not only in the network tab but also in the console.

**Comment by CoreyVincent** [comment]
@undernightcore 
![image](https://github.com/adonisjs/core/assets/11997743/6facfaf4-05df-44a9-b223-9131d9fe1376)

**Comment by CoreyVincent** [comment]
@undernightcore @thetutlage Any thoughts?
