### ISSUE TITLE
Add decorators to the framework

### ISSUE THREAD

**Issue by NourEldinShobier** [adonisjs/core#3300]
Hi,

Firstly I would like to thank you for this awesome framework, it's really easy to pick up especially for those who come from Rails background like me.

As for the feature I'm requesting - Even though I love rails, but I still think that NestJS has some features that make it unique. One of them is using `Decorators` to do almost all the difficult stuff: extracting data from requests (params, body, ...) in controllers, schema validation ( dtos ), ...etc.

So I was thinking that combining the best of both worlds, would give a huge edge to `AdonisJS`

**Comment by RomainLanz** [comment]
Hey @NourEldinShobier! 👋🏻 

First of all, there are decorators for features that need validators.

Then, if you would like to use a decorator for other stuff, feel free to install libraries that add those or code them yourself. You are free to do whatever you want.

The usage of decorators in Nest is mostly overkill, making your code unreadable and very verbose. This is not what we want.

Lastly, this is not an issue with the framework at all. So if you would like to discuss that, then create [a discussion thread](https://github.com/adonisjs/core/discussions), if you would like to propose a change in how AdonisJS behaves, then [create an RFC](https://github.com/adonisjs/rfcs).

Closing since this is not an issue with the framework.
