### ISSUE TITLE
capitalCase and sentenceCase breaks accented characters 

### ISSUE THREAD

**Issue by galaczi** [adonisjs/core#3636]
## Package version
```
├── @adonisjs/assembler@5.4.2
├── @adonisjs/auth@8.0.12
├── @adonisjs/bouncer@2.2.6
├── @adonisjs/core@5.5.3
├── @adonisjs/lucid-slugify@2.1.4
├── @adonisjs/lucid@17.0.1
├── @adonisjs/mail@7.2.5
├── @adonisjs/repl@3.1.9
├── @adonisjs/session@6.1.4
├── @adonisjs/shield@7.0.8
├── @adonisjs/view@6.1.2
```

## Node.js and npm version
v16.14.1

## Sample Code (to reproduce the issue)
```
  {{capitalCase('hír')}}
  {{sentenceCase('hír')}}
```
The above will result in ``H R`` and  ``H r``, so a space is returned instead of the correct case of the letter ``í``. Additionally I tested with ``ű`` and ``á``, both are broken.

**Comment by Julien-R44** [comment]
The problem comes from this package: https://github.com/blakeembrey/change-case/issues/103

Basically we re-export some functions from this package. Unfortunately, it is not possible to pass options to our abstractions.

A temporary solution for you could be to download this package: https://www.npmjs.com/package/case-anything and create your own helpers for edge.
