### ISSUE TITLE
Adding some default Controllers, Models and Migrations.

### ISSUE THREAD

**Issue by sahil0571** [adonisjs/core#3719]
Hello development team (Sorry for my bad English),

As Adonis Js is very good JavaScript framework with same structure as Laravel. I just want to add a suggestion if you guys don't mind.
If we see Laravel there are some default migrations, models and controllers premade to take some quick look at the structure of the framework and by using them some of the packages are also developed which provides starter kits for example login and signup using Laravel Jetstream and breeze.
It will be easier for the new comers to easily understand how framework works and what directories are having which type of files and what and how does it processes requests.  
I am also a Laravel developer and I am not so perfect with JavaScript right now that I can contribute to the framework but as a Laravel developer I would say this framework is great and has a lot of similarities to it and its a lot faster too. Thank you guys for making. I will try to support this framework as much as I can.
I think Node.js lacked such a framework, to be honest I found developing with Express tedious and boring. Hope it gets more popular - again, thanks for making this beautiful framework.

**Comment by thetutlage** [comment]
Hello @sahil0571 👋

Thanks for your sharing your suggestions and yes we do have plans to make it even easier for new comers to quickly build applications without digging too deep into the framework.

I will close this issue for now, since there is nothing actionable right away. The ideas you have shared are great and interesting, but it will take some time to plan and work on them.

Thanks again 🙂
