### ISSUE TITLE
[Feature] Apply multiple request types to a route.

### ISSUE THREAD

**Issue by iyashpal** [adonisjs/core#3840]
## Why this feature is required (specific use-cases will be appreciated)?
There are situations when we need multiple request types on a particular route. At the moment we have to write the same route multiple times to apply the different request types. i.e 
```javascript
Route.get('cart', 'CartsController.show').as('carts.show')
Route.put('cart', 'CartsController.show')

// PUT | PATCH     /cart    --------------------   carts.show       
```
If possible it can be utilized like this. Similar to the Laravel framework.
```javascript
Route.match(['get', 'put'], 'cart', 'CartsController.show').as('carts.show')

// PUT | PATCH     /cart    --------------------   carts.show       
```

## Have you tried any other workarounds?
No

## Are you willing to work on it with little guidance?
Not so sure.

**Comment by RomainLanz** [comment]
Hey @iyashpal! 👋🏻 

I am not sure you have read the doc about the `routing` system on Adonis.

You can use the `route()` method to map a route to multiple HTTP verbs.

```ts
Route.route('cart', ['GET', 'PUT'], async () => {
  // ...
})
```

📖  https://docs.adonisjs.com/guides/routing#rest-of-the-http-verbs

Also, this is more a question than an issue with the framework itself.
Since we want to keep this space clean, please use [GitHub Discussion](https://github.com/adonisjs/core/discussions) or the [Discord Server](https://discord.gg/vDcEjq6) for this kind of request.
