### ISSUE TITLE
export HttpExceptionHandler for public api

### ISSUE THREAD

**Issue by bingtsingw** [adonisjs/core#3961]
Hi, could you please review this pr again: https://github.com/adonisjs/core/pull/3951

## Why this feature is required (specific use-cases will be appreciated)?
I want to develop a third party packages which extends `HttpExceptionHandler`

```typescript
import { HttpExceptionHandler } from '@adonisjs/core/build/src/HttpExceptionHandler';
```

This would throw an error if not export on `@adonisjs/core`'s  `package.json`.

## Are you willing to work on it with little guidance?
Yes: https://github.com/adonisjs/core/pull/3951

**Comment by bingtsingw** [comment]
@thetutlage

**Comment by thetutlage** [comment]
This should already work because we have this catch all pattern defined https://github.com/adonisjs/core/blob/develop/package.json#L24.

Following is a screenshot from my code editor and there are no import errors

<img width="873" alt="CleanShot 2022-11-10 at 12 09 46@2x" src="https://user-images.githubusercontent.com/1706381/201018518-3d740015-c203-4733-b324-33d2235376e7.png">

**Comment by thetutlage** [comment]
Closing since not actionable
