### ISSUE TITLE
Controller name registration made easy

### ISSUE THREAD

**Issue by GiorgiKumelashvili** [adonisjs/core#3983]
## Why this feature is required (specific use-cases will be appreciated)?
I would like to add more type checking to registering controller names in the routes.ts file. For example, the current way of doing it is

```ts
import Route from '@ioc:Adonis/Core/Route'

Route.get('posts', 'PostsController.index') // strings are bad, Laravel has already removed this kind of thing
```

However by using this method

```ts
interface AnyClass<T> extends Function {
  new (...args: any[]): T;
}

function fields<T>(Cls: AnyClass<T>) {
  return new Proxy(Cls, {
    get: (cls: AnyClass<T>, prop: string) => cls.name + '.' + prop,
  }) as {
    [P in keyof T]: P;
  };
}
```

We can make controller name registration more pleasant and checked (no typos allowed). 

```ts
class UserController {
  findAll() {}
}


// used above method
const userConrollerFields = fields(UserController);

// prompted findAll name by intelisense in any ide or code editor !!!
console.log(userConrollerFields.findAll); // UserController.findAll

```

As you can see, it's much more convenient to use this way rather than second-guessing names in strings.

## Are you willing to work on it with little guidance?
Surely

**Comment by Julien-R44** [comment]
Please read the following
https://docs.adonisjs.com/guides/controllers#controller-routes-reference

Note that you can also use the [VScode extension](https://github.com/Julien-R44/adonis-vscode-extension) to have autocomplete on controller names and their methods. This is not the equivalent of a real type-safety but still a good compromise.

**Comment by GiorgiKumelashvili** [comment]
Sure, but neither of them solves the real issue, you can miss a typo and the project will still be built without alerting you to the mistake.

**Comment by Julien-R44** [comment]
I'm not sure if you read the part of the documentation I sent you, which explains why this choice was made. Because the solution you suggest will have exactly the problems mentioned. No lazy loading, and the obligation to import all your controllers in your route file.

That said, you are perfectly free not to use reference strings if these two problems don't bother you. You just have to make a little helper in your codebase, as you suggested, and voila, you will have type safety.

Also, read this please :
https://docs.adonisjs.com/guides/controllers#betting-on-the-typescript-future

Will close the issue, I think everything was said 🙂
