### ISSUE TITLE
Metrics endpoint via prom-client or opentelemetry

### ISSUE THREAD

**Issue by OneCricketeer** [adonisjs/core#4138]
## Why this feature is required (specific use-cases will be appreciated)?

I see you have docs on a basic health check. This is great, but how can I add RED or USE metrics for really monitoring the service?

Prometheus/Grafana or DataDog are very commonly used for collecting and viewing metrics and traces, and those metrics can be used for setting up service alerts. Without metrics, we don't feel confident to deploy our services into production. 

## Have you tried any other work arounds?

`prom-client` and `open-telemetry/opentelemetry-js` Node libraries exist, and seem to have ways to work with any server, but many examples appear to be ExpressJS focused.

**Comment by Julien-R44** [comment]
I made a package to export some generic metrics to Adonis via Prometheus : https://github.com/Julien-R44/adonis5-prometheus
It also allows you to export your own metrics easily

For OpenTelemetry, I think doing an integration would be much more complicated. Because we don't use express or fastify internally, libraries for which OpenTelemetry offers plugins. And there are no packages in the ecosystem at the moment that I know of.

Anyway, for the moment, no plan to add this natively in AdonisJS.

**Comment by Julien-R44** [comment]
No, it doesn't mean that, it means that you'll have to implement it yourself or look at what's already available. For example I see that open telemetry has a plugin for knex.
