### ISSUE TITLE
Unknown property requestData on RequestContract

### ISSUE THREAD

**Issue by TeoConan** [adonisjs/core#4309]
## Package version
`"@adonisjs/core": "^5.9.0"`
## Node.js and npm version
Node : `v20.9.0`
Npm : `10.2.3`

## Sample Code (to reproduce the issue)
Hello everyone, this is not a big bug but I think a property is missing in the `RequestContract` (in `HttpContextContract`)
I was try to "reparse" a post parameter to be sure it's a number before to validate it with `request.validate` :
``` typescript
public async register({ request, auth, response }: AppHttpContextContract) {
    request.requestData.role = parseInt(request.requestData.role);
    // ...
}
```
Here my route to give more context :
``` typescript
Route.post('/register', 'AuthController.register').middleware(
    'throttle:register'
);
```
My problem is I have a ts error that say `Property 'requestData' does not exist on type 'RequestContract'`
But the funny part is that my code works absolutely fine like this
Am I doing it wrong or is a prop missing ?
I maybe can do a MR to fix it if I'm right

Thanks in advance and thanks for Adonis, it's a nice framework

**Comment by aikrom** [comment]
Hello! 

You ignore Typescirpt error, right? If it is true, I think there is nothing to fix, `requestData` is a private property of the `Request` class. You ignore the error and your code works because Javascript classes do not have the "private" access modifier that can be use in Typescirpt. So for Javascript `requestData` property exists, it is accessible and everything is fine.

I recommend to read the code of the [Request](https://github.com/adonisjs/http-server/blob/develop/src/Request/index.ts) class where you can find better way to manage the request data.

**Comment by aikrom** [comment]
By the way, before validation you don’t need to parse the number from the request data, because the validator does this.

**Comment by TeoConan** [comment]
Thank you for your answer,
I'll check it out
But that's weird it work even if the property is private 😄
