### ISSUE TITLE
[v6] Bouncer make:policy command is not defined    

### ISSUE THREAD

**Issue by shankiflang** [adonisjs/core#4354]
### Package version

"@adonisjs/core": "^6.2.1"
"@adonisjs/bouncer": "^3.1.0"

### Describe the bug

I installed adonis `"@adonisjs/core": "^6.2.1"` via `pnpm create adonisjs@latest hello-world`, installed bouncer and configured it. Then when I try to create a policy as the doc says: https://docs.adonisjs.com/guides/commands-reference#makepolicy, I get this error:
![image](https://github.com/adonisjs/core/assets/32774804/54143892-2f67-4d14-b88c-f1439fe19a2c)

**Comment by Julien-R44** [comment]
this was a bug with the configure command for Bouncer. has been fixed in the latest release 3.1.1 : https://github.com/adonisjs/bouncer/releases/tag/v3.1.1

You can either :
- manually add `@adonisjs/bouncer/commands` to your `commands` entry in the `adonisrc.ts` file
- or update @adonisjs/bouncer to 3.1.1 and run `node ace configure @adonisjs/bouncer` agai
